baseURL = "https://homestacklab.fr/"
locale = "fr-FR"
title = "HomeStackLab"
theme = "PaperMod"

# ---- FRONTMATTER ----
[frontmatter]
lastmod = [":git", "lastmod", "date", "publishDate"]

# ---- MARKDOWN / GOLDMARK ----
[markup.goldmark.renderer]
unsafe = true

# ---- NAVIGATION ----
[[menu.main]]
identifier = "linux"
name = "Systèmes"
url = "/system/"
weight = 10
[[menu.main]]
identifier = "network"
name = "Réseau"
url = "/network/"
weight = 20
[[menu.main]]
identifier = "services"
name = "Services"
url = "/services/"
weight = 30
[[menu.main]]
identifier = "smarthome"
name = "Domotique"
url = "/smarthome/"
weight = 40
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 50

# ---- PAPERMOD THEME ----
# [params]
# defaultTheme = "auto"
# mainSections = ["system", "network", "services", "smarthome"] 
# hideSummary = true
# ShowReadingTime = true
# ShowShareButtons = true
# ShowBreadCrumbs = true
# ShowCodeCopyButtons = true
# ShowPostNavLinks = false
# showThemeToggle = true
# ShowToc = true
# TocOpen = true
# [params.homeInfoParams]
# Title = "Build and Forget."
# Content = """
# Pour ceux qui aiment construire des architectures solides, puis les oublier.<br>
# Des solutions vécues, testées et éprouvées pour la maison :<br>
# <a href="/system/">systèmes</a>,
# <a href="/network/">réseau</a>,
# <a href="/services/">services</a>
# et <a href="/smarthome/">domotique</a>.
# """
